name: update cv pdf
on:
  workflow_dispatch:
  push:

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: npm ci
      - run: npm run build:pdf

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: github.ref == 'refs/heads/main'
        with:
          commit_author: GitHub Actions <actions@github.com>
          commit_message: Update CV pdf
